SELECT SUBSTRING(
    (SELECT ', ' + QUOTENAME(COLUMN_NAME)
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'Dim_Customers'
        ORDER BY ORDINAL_POSITION
        FOR XML path('')),
    3,
    200000);

SELECT SUBSTRING(
    (SELECT ', ' + QUOTENAME(COLUMN_NAME)
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'Dim_Products'
        ORDER BY ORDINAL_POSITION
        FOR XML path('')),
    3,
    200000);

SELECT SUBSTRING(
    (SELECT ', ' + QUOTENAME(COLUMN_NAME)
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'Dim_Employees'
        ORDER BY ORDINAL_POSITION
        FOR XML path('')),
    3,
    200000);


SELECT SUBSTRING(
    (SELECT ', ' + QUOTENAME(COLUMN_NAME)
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'Dim_Categories'
        ORDER BY ORDINAL_POSITION
        FOR XML path('')),
    3,
    200000);

